/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Main_calculateMean
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     Main
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Main_calculateSTDDev
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
